### ISSUE TITLE
Add credits to the repository owner and copyright footer below.

### ISSUE THREAD

**Issue by rajatrajputdev** [bhanusingh008/flappy-bird#10]
A footer will look good and will let other users know about the repository. Kindly mark it under hacktoberfest.

**Comment by bhanu-io** [comment]
I have marked it as "hacktoberfest" in the topic section in about. Do i have to mark it anywhere else too? Also check on your hacktober profile, it must be saying "waiting..."  alongside PR, smthing like that. If yes you're good to go

**Comment by rajatrajputdev** [comment]
Actually, you have to manually label issues as hacktoberfest to bring them under hacktoberfest.

**Comment by bhanu-io** [comment]
RIght, the issue is labelled now
