### ISSUE TITLE
Score Positioning

### ISSUE THREAD

**Issue by rajatrajputdev** [bhanusingh008/flappy-bird#4]
Hey there! I was playing this game when I realized that the score display should not be at left but rather some other position where it is fairly visible. So I can fix it and I'd like to contribute.

Kindly assign me this under Hacktoberfest! Thank you! @bhanusingh008

**Comment by bhanu-io** [comment]
Sure

**Comment by rajatrajputdev** [comment]
I'll work on it and submit the code, can you please assign it under Hacktoberfest?

**Comment by bhanu-io** [comment]
Yes, this repo is participating in the hacktober fest.

**Comment by rajatrajputdev** [comment]
@bhanusingh008 I've fixed this issue, kindly check! :)
